---
openapi: 3.0.3
info:
  title: Common Error Definitions
  version: 1.0.0

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: object
          required:
            - code
            - message
          properties:
            code:
              type: string
              description: Unique error code
            message:
              type: string
              description: Human-readable error message
            details:
              type: array
              items:
                type: object
                properties:
                  field:
                    type: string
                    description: Field name that caused the error
                  message:
                    type: string
                    description: Specific error message for the field
            timestamp:
              type: string
              format: date-time
              description: Error occurrence timestamp