apiVersion: v1
kind: Service
metadata:
  name: bookingservice
  labels:
    app: bookingservice
spec:
  selector:
    app: bookingservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80