apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: paymentservice:latest # Replace with your actual image name and tag
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_HTTP_PORT
              value: "80"
            - name: Consul__Host
              value: "http://consul:8500" # Referencing the Consul service
            - name: Consul__ServiceName
              value: "PaymentService"