apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
      name: http
    - protocol: UDP
      port: 8600
      targetPort: 8600
      name: udp