apiVersion: v1
kind: Service
metadata:
  name: notificationservice
  labels:
    app: notificationservice
spec:
  selector:
    app: notificationservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80