apiVersion: v1
kind: Service
metadata:
  name: reportingservice
  labels:
    app: reportingservice
spec:
  selector:
    app: reportingservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80